spring.application.name=healthcare
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_app
spring.datasource.username=root
spring.datasource.password=pinka11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openai.api.key=${OPENAI_API_KEY}